export const tourismAssets=[
 {id:'tour-hanbit',name:'한빛탑',district:'유성구',feature:'전망대 원반 · 첨탑',page:4},
 {id:'tour-expo-bridge',name:'엑스포다리',district:'유성구·서구',feature:'빨강·파랑 쌍아치 · 교량',page:4},
 {id:'tour-arboretum',name:'한밭수목원',district:'서구',feature:'온실 · 연못 · 수목',page:4},
 {id:'tour-art-museum',name:'대전시립미술관',district:'서구',feature:'전시동 · 유리 입구 · 수공간',page:7},
 {id:'tour-arts-center',name:'대전예술의전당',district:'서구',feature:'공연장 · 열주 · 넓은 지붕',page:3},
 {id:'tour-science',name:'국립중앙과학관',district:'유성구',feature:'전시관 · 천체관 돔 · 로켓',page:4},
 {id:'tour-hot-spring',name:'유성온천 족욕체험장',district:'유성구',feature:'족욕 수로 · 벤치 · 그늘 구조물',page:7},
 {id:'tour-yurim',name:'유림공원',district:'유성구',feature:'연못 · 정자 · 산책 공간',page:5},
 {id:'tour-observatory',name:'대전시민천문대',district:'유성구',feature:'관측 돔 · 관측창',page:7},
 {id:'tour-geology',name:'지질박물관',district:'유성구',feature:'박물관 · 암석 전시 표현',page:6},
 {id:'tour-skyroad',name:'으능정이 문화의 거리',district:'중구',feature:'스카이로드 미디어 캐노피 · 상가',page:4},
 {id:'tour-sungsimdang',name:'성심당 본점',district:'중구',feature:'베이커리 외관 · 차양 · 쇼윈도',page:5},
 {id:'tour-heritage',name:'대전근현대사전시관',district:'중구',feature:'중앙 현관 · 대칭 입면',page:5},
 {id:'tour-temiorae',name:'테미오래',district:'중구',feature:'관사 · 지붕 · 정원',page:5},
 {id:'tour-oworld',name:'대전 오월드',district:'중구',feature:'입구 · 놀이공원 상징 표현',page:5},
 {id:'tour-ppuri',name:'뿌리공원',district:'중구',feature:'성씨 조형물 · 잔디 · 정자',page:5},
 {id:'tour-uam',name:'우암사적공원',district:'동구',feature:'전통 건축 · 연못 · 담장',page:5},
 {id:'tour-dongchundang',name:'동춘당',district:'대덕구',feature:'전통 목구조 · 기와 · 담장',page:8},
 {id:'tour-daedong',name:'대동하늘공원',district:'동구',feature:'풍차 · 전망 공간',page:5},
 {id:'tour-lee-ungno',name:'이응노미술관',district:'서구',feature:'분절된 전시동 · 중정',page:7},
 {id:'tour-jangtae',name:'장태산자연휴양림',district:'서구',feature:'메타세쿼이아 · 스카이워크 표현',page:7},
 {id:'tour-gyejok-trail',name:'계족산황톳길',district:'대덕구',feature:'황토 산책로 · 숲',page:7},
 {id:'tour-gyejok-fort',name:'계족산성',district:'대덕구',feature:'석축 · 산성 능선',page:6},
 {id:'tour-daecheong',name:'대청호반',district:'대덕구',feature:'호수 · 전망 정자 · 수변',page:2},
 {id:'tour-meditation',name:'대청호 명상정원',district:'동구',feature:'호숫가 데크 · 정원',page:1},
 {id:'tour-manin',name:'만인산휴양림',district:'동구',feature:'숲 · 현수교 표현',page:1},
 {id:'tour-sangso',name:'상소동 산림욕장',district:'동구',feature:'돌탑 군락 · 숲길',page:8},
 {id:'tour-gapcheon',name:'갑천생태호수공원',district:'서구',feature:'호수 · 산책 데크 · 잔디',page:1},
 {id:'tour-heredium',name:'헤레디움',district:'동구',feature:'근대 전시관 · 세로 창',page:3},
 {id:'tour-city-history',name:'대전시립박물관',district:'유성구',feature:'전시동 · 중정 · 입구',page:6},
 {id:'tour-currency',name:'화폐박물관',district:'유성구',feature:'박물관 · 주화 상징 표현',page:6},
 {id:'tour-education',name:'한밭교육박물관',district:'동구',feature:'학교형 전시동 · 대칭 입면',page:6},
 {id:'tour-prehistory',name:'대전선사박물관',district:'유성구',feature:'전시관 · 선사 유적 표현',page:6},
 {id:'tour-dunsan',name:'둔산선사유적공원',district:'서구',feature:'움집 · 유적 터 · 수목',page:6},
 {id:'tour-cemetery',name:'국립대전현충원',district:'유성구',feature:'현충문 · 추모 공간 표현',page:1},
 {id:'tour-big-tree',name:'보문산큰나무전망대',district:'중구',feature:'분기형 전망 구조 · 전망 데크',page:1},
 {id:'tour-worldcup',name:'대전월드컵경기장',district:'유성구',feature:'축구장 · 관람석 · 지붕',page:2},
 {id:'tour-ballpark',name:'대전한화생명볼파크',district:'중구',feature:'야구장 · 관람석 · 조명탑',page:2},
 {id:'tour-jokbo',name:'한국족보박물관',district:'중구',feature:'박물관 · 유리 전면 · 광장',page:3},
 {id:'tour-hyo',name:'대전효문화진흥원',district:'중구',feature:'문화 전시동 · 전면 열주',page:3},
 {id:'tour-hoedeok',name:'회덕향교',district:'대덕구',feature:'대성전 · 강학 공간 · 문',page:3},
 {id:'tour-jinjam',name:'진잠향교',district:'유성구',feature:'홍살문 · 기와 건축 · 담장',page:3},
 {id:'tour-sunghyeon',name:'숭현서원',district:'유성구',feature:'서원 중정 · 강당 · 문',page:3},
 {id:'tour-hoyeon',name:'소대헌·호연재 고택',district:'대덕구',feature:'고택 · 툇마루 · 안마당',page:6},
 {id:'tour-literature',name:'대전문학관',district:'동구',feature:'문학 전시동 · 책 상징 표현',page:1},
 {id:'tour-temi-literature',name:'대전테미문학관',district:'중구',feature:'작은 전시관 · 정원',page:1},
 {id:'tour-woodcraft',name:'대전 목재문화체험장',district:'중구',feature:'목재 외장 · 체험관',page:8},
 {id:'tour-march38',name:'3·8민주의거기념관',district:'중구',feature:'기념관 · 수직 입면 · 기념 벽',page:1},
 {id:'tour-narae',name:'대전전통나래관',district:'동구',feature:'문화 전시동 · 격자 전면',page:2},
 {id:'tour-yeonjeong',name:'대전시립연정국악원',district:'서구',feature:'공연장 · 곡선 처마 표현',page:2},
] as const;
export const tourismProject='https://higgsfield.ai/3d-jutsu/f7ed4222-b82c-45a8-9ded-b1a447051fc7';
